### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by CruaverVoidDrake** [uyjulian/MinecraftX-RAY#4]
Entity X-ray. While the xray does show entities through blocks, I'd like an additional add on to it to allow for seeing exclusively entities. It seems reasonable and possible, as demonstrated by CJB's x-ray mod.

**Comment by Brottweiler** [comment]
Make a better title. :stuck_out_tongue:

**Comment by CruaverVoidDrake** [comment]
I am not good with names. I was figuring that an entity x-ray would be more efficient than a block x-ray since it only focuses on entities.

**Comment by Brottweiler** [comment]
Your title is literally "Suggestion", which doesn't show what this issue is about at all. "Suggestion: Entity Xray" would be better.

**Comment by uyjulian** [comment]
I don't edit the entity rendering code, it's outside the scope of this mod.
